openapi: 3.0.3
info:
  title: Lysine API
  version: 1.0

paths:
  /reimbursements:
    get:
      tags:
        - Reimbursement
      summary: Get reimbursement
      operationId: getReimbursement
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReimbursementResponse'
    post:
      tags:
        - Reimbursement
      summary: submit reimbursement request with attached docs and label
      operationId: submitReimbursement
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              required:
                - reimbursement
              properties:
                reimbursement:
                  $ref: '#/components/schemas/ReimbursementDto'
            encoding:
              reimbursement:
                contentType: application/json
      responses:
        '200':
          description: Files uploaded successfully
          content:
            application/json:
              schema:
                $ref : '#/components/schemas/ReimbursementDto'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /approve:
    get:
      tags:
        - Reimbursement
      summary: Get reimbursement for approver
      operationId: getReimbursementForApprover
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReimbursementResponse'


components:
  schemas:
    Status:
      type: string
      enum:
        - PENDING
        - APPROVED
        - CLOSED
        - REJECTED
        - SUBMIT
        - PROCESSING
        - CANCEL
        - DELETED

    ReimbursementType:
      type: string
      enum:
        - REGULAR
        - SALE
        - MATERIAL
        - LOGISTICS
        - MISCELLANEOUS

    ReimbursementDocumentDto:
      type: object
      properties:
        id:
          type: string
        label:
          type: string
        file:
          type: string
          format: binary
        filePath:
          type: string
        reimbursementId:
          type: string

    ReimbursementDto:
      type: object
      properties:
        id:
          type: string
        status:
          $ref: '#/components/schemas/Status'
        reimbursementType:
          $ref: '#/components/schemas/ReimbursementType'
        userId:
          type: string
        description:
          type: string
        documents:
          type: array
          items:
            $ref: '#/components/schemas/ReimbursementDocumentDto'

    ReimbursementResponse:
      type: object
      properties:
        success:
          type: boolean
          example: true
        message:
          type: string
          example: "Files uploaded successfully"
        status:
          $ref: '#/components/schemas/Status'

    ApproveDto:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        email:
          type: string
    Error:
      type: object
      properties:
        success:
          type: boolean
          example: false
        error:
          type: string
          example: "Validation failed"